name: list_of_users_test_task
description: "task for Tark"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  freezed: ^2.5.2
  injectable: ^2.4.2
  dio: ^5.5.0+1
  retrofit: ^4.1.0
  get_it: ^7.7.0
  retrofit_generator: ^8.1.1
  json_annotation: ^4.9.0
  injectable_generator: ^2.6.1
  freezed_annotation: ^2.4.2
  logger: ^2.3.0
  paginated_list: ^1.2.3
  slide_switcher: ^1.1.2
  animated_toggle_switch: ^0.8.2
  animated_search_bar: ^2.7.2
  github_sign_in_plus: ^0.0.2
  flutter_dotenv: ^5.1.0
  bloc_concurrency: ^0.2.5

dev_dependencies:
  #  flutter packages pub run build_runner build --delete-conflicting-outputs

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true
  assets:
    - .env
